{% set name = "asset" %}
{% set version = "0.6.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asset-{{ version }}.tar.gz
  sha256: ec56cbf77931cb74d063848531db782f6f0fe1272d1f47f322c15efd0fa732ea

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - aadict >=0.2.2
    - globre >=0.1.5
    - python >={{ python_min }}
    - six >=1.10.0

test:
  imports:
    - asset
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/metagriffin/asset
  summary: A package resource and symbol loading helper library.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nelson-liu
